# 1 ST QUESTION

In [1]:
lst_nums = [10,17,19,24,36]
print(lst_nums)

[10, 17, 19, 24, 36]

In [2]:
lst_nums1 = []
lst_nums1.append(lst_nums)
print(lst_nums1)

[[10, 17, 19, 24, 36]]

In [3]:
lst_nums.extend([60,70,80,90,100])
print(lst_nums)

[10, 17, 19, 24, 36, 60, 70, 80, 90, 100]

In [4]:
lst_nums.insert(21,28)
print(lst_nums)

[10, 17, 19, 24, 36, 60, 70, 80, 90, 100, 28]

In [5]:
lst_nums.remove(24)
print(lst_nums)

[10, 17, 19, 36, 60, 70, 80, 90, 100, 28]

In [6]:
lst_nums.pop()

28

In [7]:
lst_nums[3]

36

In [8]:
lst_nums.count(70)

1

In [9]:
lst_nums.sort()
print(lst_nums)

[10, 17, 19, 36, 60, 70, 80, 90, 100]

In [10]:
lst_nums.reverse()
print(lst_nums)

[100, 90, 80, 70, 60, 36, 19, 17, 10]

In [11]:
lst_nums.clear()
print(lst_nums)

[]

# 2 ND QUESTION

In [12]:
tup = ("mani","gopi","kalyan")
tup

('mani', 'gopi', 'kalyan')

In [13]:
tup[1]

'gopi'

In [14]:
tup[1]=("Nani")
tup

TypeError: 'tuple' object does not support item assignment

 EXPLANATION: In the tuple we cannot change the values.

# 3 RD QUESTION

In [ ]:
S1 = (11,52,29,34,23,11,8,4,29,34)
print(S1)
set(S1)

EXPLANATION: In sets the duplicate values dosennot exists it eleminates the duplicate values and arranges in Asscending order

# 4 TH QUESTION

In [15]:
D1 = {"name":"mani","age":23,"city":"ongole"}
print(D1)

{'name': 'mani', 'age': 23, 'city': 'ongole'}

In [16]:
D1["age"] = 24
print(D1)

{'name': 'mani', 'age': 24, 'city': 'ongole'}

In [17]:
D1["email"] = "123@gmail.com"
print(D1)

{'name': 'mani', 'age': 24, 'city': 'ongole', 'email': '123@gmail.com'}

In [18]:
D1

{'name': 'mani', 'age': 24, 'city': 'ongole', 'email': '123@gmail.com'}

# 5 TH QUESTION

In [33]:
age = int(input("enter the age:"))
if age  >= 18 :
    print("person is eligible for vote")
else:
    print("person is not eligible for vote")

enter the age: 22

person is eligible for vote

# 6 TH QUESTION

In [32]:
marks = int(input("enter the marks:")) 
if marks >= 90:
    print('A')
elif marks >= 75 and marks < 90: 
    print('B')
elif marks >= 50 and marks < 75: 
    print('C')
else:
    print("Fail")

enter the marks: 73

C

# 7 TH QUETION

In [38]:
a = int(input("enter the number:"))
if a > 0 :
    if a%2 ==0:
        print("positive and even number")
    else:
        print("positive and odd number")
elif a ==0:
    print("zero")
else:
    print("Negative")

enter the number: -4

Negative

# 8 TH QUESTION

In [39]:
import numpy as np

In [42]:
a = np.array([10,20,40,60,90])
a

array([10, 20, 40, 60, 90])

In [43]:
num = ([1,2,3,4,5])

In [45]:
np.array(num)

array([1, 2, 3, 4, 5])

In [48]:
b = np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

# 9 TH QUESTION

In [50]:
C = np.random.randint(0,100,size=(4,4))
C

array([[67, 87, 80, 68],
       [62, 20, 20,  8],
       [77,  1,  3, 99],
       [10, 45, 32, 83]])

# 10 TH QUESTION

In [59]:
E = np.array([[14,18,24],[21,26,19],[31,27,22]])
E

array([[14, 18, 24],
       [21, 26, 19],
       [31, 27, 22]])

In [60]:
import pandas as pd
df = pd.DataFrame(E)
df

    0   1   2
0  14  18  24
1  21  26  19
2  31  27  22

In [61]:
df.columns =['A','B','C']
df

    A   B   C
0  14  18  24
1  21  26  19
2  31  27  22